site_name: Phil's Online Notebook
site_url: https://bryanpc01.github.io/Notebook/
repo_url: https://github.com/bryanpc01/Notebook
repo_name: bryanpc01/Notebook
theme:
  name: material
  font:
    text: Noto Sans
    code: JetBrains Mono
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: deep orange
      accent: orange

    # Palette toggle for light theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep orange
      accent: orange

    # Palette toggle for dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
      primary: deep orange
      accent: orange
  features:
    - header.autohide
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - navigation.sections
plugins:
  - search
extra:
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/phil-bryan
    - icon: fontawesome/brands/github
      link: https://github.com/bryanpc01
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/phil_nass/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/bryanceal
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zRNZ43Kh
copyright: >
  Copyright &copy; 2024 - Phil Bryan –
  <a href="#__consent">Change cookie settings</a>
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
